## ex1

![Image](images/image1.png)

In [2]:
import numpy as np
data = np.array([[4, 6, 8],
           [5, 7, 0]])

# 1. Centrer et réduire les données
data_centered = data - np.mean(data, axis=1, keepdims=True)
data_standardized = data_centered / np.std(data_centered, axis=1, keepdims=True)

# 2. Calcul de la matrice des variances-covariances
cov_matrix = np.cov(data_standardized)

# 3. Calcul de la matrice des corrélations
cor_matrix = np.corrcoef(data_standardized)

# 4. Calcul des valeurs propres et vecteurs propres
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Impression des résultats
print("Données centrées et réduites :\n", data_standardized)
print("\nMatrice des variances-covariances :\n", cov_matrix)
print("\nMatrice des corrélations :\n", cor_matrix)
print("\nValeurs propres :\n", eigenvalues)
print("\nVecteurs propres :\n", eigenvectors)



Données centrées et réduites :
 [[-1.22474487  0.          1.22474487]
 [ 0.33968311  1.01904933 -1.35873244]]

Matrice des variances-covariances :
 [[ 1.5        -1.04006287]
 [-1.04006287  1.5       ]]

Matrice des corrélations :
 [[ 1.         -0.69337525]
 [-0.69337525  1.        ]]

Valeurs propres :
 [0.45993713 2.54006287]

Vecteurs propres :
 [[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]


## ex2
![image.png](images/image3.png)

In [2]:
import numpy as np

Math = [6, 1, 4, 5, 3, 2, 9, 7, 8, 10, 11]
Francais = [2, 6, 5, 3, 4, 1, 8, 9, 7, 10, 11]
donnees = np.array([Math, Francais]).T
taille_matrice = donnees.shape
print("1. Taille de la matrice individus/variables :", taille_matrice)
moyennes = np.mean(donnees, axis=0)
ecart_types = np.std(donnees, axis=0)
print("2. Moyennes des variables :", moyennes)
print("   Écart-types des variables :", ecart_types)


matrice_covariance = np.cov(donnees, rowvar=False)
matrice_correlation = np.corrcoef(donnees, rowvar=False)
print("3. Matrice de variance-covariance :\n", matrice_covariance)
print("   Matrice de corrélation :\n", matrice_correlation)


valeurs_propres, vecteurs_propres = np.linalg.eig(matrice_covariance)
print("4. Valeurs propres de la matrice de variance-covariance :\n", valeurs_propres)
print("   Vecteurs propres de la matrice de variance-covariance :\n", vecteurs_propres)
contribution_axes = valeurs_propres / np.sum(valeurs_propres)
print("5. Contribution de chaque axe principal à l'inertie du nuage :\n", contribution_axes)

nouveaux_axes_principaux = vecteurs_propres
nouvelles_composantes_principales = np.dot(donnees, nouveaux_axes_principaux)
print("6. Nouveaux axes principaux :\n", nouveaux_axes_principaux)
print("   Nouvelles composantes principales :\n", nouvelles_composantes_principales)


1. Taille de la matrice individus/variables : (11, 2)
2. Moyennes des variables : [6. 6.]
   Écart-types des variables : [3.16227766 3.16227766]
3. Matrice de variance-covariance :
 [[11.   8.3]
 [ 8.3 11. ]]
   Matrice de corrélation :
 [[1.         0.75454545]
 [0.75454545 1.        ]]
4. Valeurs propres de la matrice de variance-covariance :
 [19.3  2.7]
   Vecteurs propres de la matrice de variance-covariance :
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
5. Contribution de chaque axe principal à l'inertie du nuage :
 [0.87727273 0.12272727]
6. Nouveaux axes principaux :
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
   Nouvelles composantes principales :
 [[ 5.65685425e+00 -2.82842712e+00]
 [ 4.94974747e+00  3.53553391e+00]
 [ 6.36396103e+00  7.07106781e-01]
 [ 5.65685425e+00 -1.41421356e+00]
 [ 4.94974747e+00  7.07106781e-01]
 [ 2.12132034e+00 -7.07106781e-01]
 [ 1.20208153e+01 -7.07106781e-01]
 [ 1.13137085e+01  1.41421356e+00]
 [ 1.06066017e+01 -7.07106781e-

## ex3
![Image](images/image.png)

In [4]:
import numpy as np
import matplotlib.pyplot as plt

points = np.array([
    [2, 10],  # A1
    [2, 5],   # A2
    [8, 4],   # A3
    [5, 8],   # A4
    [7, 5],   # A5
    [6, 4],   # A6
    [1, 2],   # A7
    [4, 9]    # A8
])

# Centres initiaux des clusters (A1, A4, A7)
initial_centers = np.array([
    [2, 10],  # C1
    [5, 8],   # C2
    [1, 2]    # C3
])

def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((point1 - point2) ** 2))

def kmeans_simple(points, initial_centers, num_clusters=3, max_iters=100):
    centers = initial_centers
    for _ in range(max_iters):
        labels = []
        for point in points:
            distances = [euclidean_distance(point, center) for center in centers]
            labels.append(np.argmin(distances))
        labels = np.array(labels)
        new_centers = []
        for i in range(num_clusters):
            cluster_points = points[labels == i]
            if len(cluster_points) > 0:
                new_center = cluster_points.mean(axis=0)
            else:
                new_center = centers[i]
            new_centers.append(new_center)
        new_centers = np.array(new_centers)
        if np.allclose(centers, new_centers):
            break
        centers = new_centers
    
    return labels, centers

labels, final_centers = kmeans_simple(points, initial_centers)

print("Assignation des clusters : ", labels)
print("Nouveaux centres des clusters : ", final_centers)

Assignation des clusters :  [0 2 1 0 1 1 2 0]
Nouveaux centres des clusters :  [[3.66666667 9.        ]
 [7.         4.33333333]
 [1.5        3.5       ]]


## ex4
![Image](images/image2.png)

In [5]:
import numpy as np

# Base de connaissance sous forme de tableau numpy
base_de_connaissance = np.array([
    [3, 5, 4, 6, 1, 1],
    [4, 6, 10, 3, 2, 2],
    [8, 3, 4, 2, 6, 3],
    [2, 1, 4, 3, 6, 3],
    [2, 5, 1, 4, 8, 2]
])

# Instance à classer (X6)
X6 = np.array([3, 12, 4, 7, 8])
def distance_euclidienne(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

# Fonction pour prédire la classe avec K-NN
def knn_predict(base_de_connaissance, X, K):
    distances = []
    for row in base_de_connaissance:
        dist = distance_euclidienne(X, row[:-1]) 
        distances.append((dist, row[-1])) 
    
    # Trier par distance et obtenir les K plus proches voisins
    distances.sort(key=lambda x: x[0])
    neighbors = distances[:K]
    counts = np.bincount([neighbor[1] for neighbor in neighbors])
    return np.argmax(counts)

# Utilisation de la fonction knn_predict pour prédire la classe de X6 avec K = 1 et K = 3
classe_k1 = knn_predict(base_de_connaissance, X6, K=1)
classe_k3 = knn_predict(base_de_connaissance, X6, K=3)

print(f"Classe de X6 selon K-NN avec K = 1 : {classe_k1}")
print(f"Classe de X6 selon K-NN avec K = 3 : {classe_k3}")


Classe de X6 selon K-NN avec K = 1 : 2
Classe de X6 selon K-NN avec K = 3 : 2
